### ISSUE TITLE
Add support for "Quotes" in tickers for all coins

### ISSUE THREAD

**Issue by dorian-coygo** [coinpaprika/coinpaprika-api-nodejs-client#1]
Is it possible to add support for quotes in the tickers for all coins? 

```
quotes | stringDefault: "USD"Example: quotes=USD%2CBTC
Comma separated list of quotes to return. Currently allowed values: BTC, ETH, USD, EUR, PLN, KRW, GBP, CAD, JPY, RUB, TRY, NZD, AUD, CHF, UAH, HKD, SGD, NGN, PHP, MXN, BRL, THB, CLP, CNY, CZK, DKK, HUF, IDR, ILS, INR, MYR, NOK, PKR, SEK, TWD, ZAR, VND, BOB, COP, PEN, ARS, ISK
```

https://api.coinpaprika.com/#tag/Tickers/paths/~1tickers/get

Looks like we would just need to modify a few lines of code:
https://github.com/coinpaprika/coinpaprika-api-nodejs-client/blob/master/index.js#L61

It also wouldn't be a breaking change since you already pass the "options" object as an argument.

**Comment by M4rcinJ** [comment]
Hello, we solved this problem with PR #3. Now you should use `getAllTickers` to get all tickers, `getTicker` was mark as deprecated. For more information please check README.md
